#!/bin/bash

# Stops on errors and prints commands

# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

sh ./configure CFLAGS="--coverage -static"
make clean ; make 


./pngtest png_tests/test1.png
gcov *.c

./pngtest png_tests/test3.png
gcov *.c

./pngtest png_tests/test4.png
gcov *.c

./pngtest png_tests/test5.png
gcov *.c


./pngtest png_tests/test8.png
gcov *.c

./pngtest png_tests/test10.png
gcov *.c

./pngtest png_tests/test19.png
gcov *.c

./pngtest png_tests/test20.png
gcov *.c

./pngtest png_tests/test23.png
gcov *.c

./pngtest png_tests/test24.png
gcov *.c

./pngtest png_tests/test25.png
gcov *.c

./pngtest png_tests/test26.png
gcov *.c

./pngtest png_tests/test27.png
gcov *.c

./pngtest png_tests/test28.png
gcov *.c

./pngtest png_tests/test29.png
gcov *.c

./pngtest png_tests/test30.png
gcov *.c

./pngtest png_tests/test31.png
gcov *.c

./pngtest png_tests/test32.png
gcov *.c

./pngtest png_tests/test33.png
gcov *.c

./pngtest png_tests/test60.png
gcov *.c

./pngtest png_tests/test61.png
gcov *.c

./pngtest png_tests/test62.png
gcov *.c

rm *.gcda pngout.png



gcov *.c

rm *.gcda pngout.png
