#!/bin/bash

# Stops on errors and prints commands

# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

sh ./configure CFLAGS="--coverage -static"
make clean ; make 

./pngtest pngtest.png
gcov *.c

./pngtest contrib/gregbook/toucan.png
gcov *.c

rm *.gcda pngout.png
